<?php
/**
 * Title: معرفی رهبر حساب
 * Slug: rahbar/hero
 * Categories: rahbar, featured
 * Inserter: yes
 */
?>
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"backgroundColor":"surface-alt","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-surface-alt-background-color has-background" style="padding-top:var(--wp--preset--spacing--60);padding-bottom:var(--wp--preset--spacing--60)"><!-- wp:columns {"align":"wide","verticalAlignment":"center"} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center","width":"62%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:62%"><!-- wp:paragraph {"textColor":"primary","fontSize":"small"} --><p class="has-primary-color has-text-color has-small-font-size"><strong><?php echo esc_html__( 'آموزش کاربردی مالی و مالیاتی', 'rahbar' ); ?></strong></p><!-- /wp:paragraph --><!-- wp:heading {"level":1,"fontSize":"hero"} --><h1 class="wp-block-heading has-hero-font-size"><?php echo esc_html__( 'دانش مالی را به تصمیم‌های بهتر تبدیل کنید', 'rahbar' ); ?></h1><!-- /wp:heading --><!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size"><?php echo esc_html__( 'دوره‌ها و راهکارهای تخصصی برای حسابداران، مدیران مالی و صاحبان کسب‌وکار.', 'rahbar' ); ?></p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#services"><?php echo esc_html__( 'مشاهده خدمات', 'rahbar' ); ?></a></div><!-- /wp:button --><!-- wp:button {"className":"is-style-outline"} --><div class="wp-block-button is-style-outline"><a class="wp-block-button__link wp-element-button" href="/contact/"><?php echo esc_html__( 'درخواست مشاوره', 'rahbar' ); ?></a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:column --><!-- wp:column {"verticalAlignment":"center","width":"38%"} --><div class="wp-block-column is-vertically-aligned-center" style="flex-basis:38%"><!-- wp:group {"className":"rahbar-card","style":{"spacing":{"padding":{"top":"var:preset|spacing|50","right":"var:preset|spacing|50","bottom":"var:preset|spacing|50","left":"var:preset|spacing|50"}}},"backgroundColor":"primary","textColor":"surface","layout":{"type":"constrained"}} --><div class="wp-block-group rahbar-card has-surface-color has-primary-background-color has-text-color has-background" style="padding:var(--wp--preset--spacing--50)"><!-- wp:heading {"textColor":"surface"} --><h2 class="wp-block-heading has-surface-color has-text-color"><?php echo esc_html__( 'مسیر روشن‌تر برای مالیات و حسابداری', 'rahbar' ); ?></h2><!-- /wp:heading --><!-- wp:paragraph --><p><?php echo esc_html__( 'محتوای دقیق، تجربه عملی و پشتیبانی در مسیر یادگیری.', 'rahbar' ); ?></p><!-- /wp:paragraph --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div>
<!-- /wp:group -->
